FROM rust:1.89-alpine3.20 AS builder

WORKDIR /app

COPY . .

RUN apk add --no-cache libressl-dev build-base musl-dev libssl3 libcrypto3 protobuf perl make libgcc libstdc++

RUN cargo build --release

FROM alpine:latest

RUN apk add --no-cache libgcc libstdc++ tzdata
# 設定環境變量，將時區設為 UTC+8
ENV TZ=Asia/Taipei

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 設定工作目錄
WORKDIR /app

# 暴露連接埠
EXPOSE 9001

# 從建構階段複製二進制檔案
COPY --from=builder /app/target/release/stock_crawler .

# ADD ./.env .
# ADD ./app.json .

COPY ./.env ./
COPY ./app.json ./

VOLUME ["/app/log","/opt/nginx/ssl/jiansoft.mooo.com"]

# 運行應用程序
CMD ["/app/stock_crawler"]